### ISSUE TITLE
BP: Rewrite built-in processors

### ISSUE THREAD

**Issue by lovromazgon** [ConduitIO/conduit#1290]
- Implement new list of processors defined in the design document
- Make sure each processor is documented and uses the specification generator to extract the specification from Go docs
- Full list:
  - [x] `field.set` - set a field in the record https://github.com/ConduitIO/conduit/pull/1371
  - [x] `field.subset.exclude` - remove fields from the record if they are on the list https://github.com/ConduitIO/conduit/pull/1371
  - [ ] `field.subset.include` - remove fields from the record if they are not on the list
  - [x] `field.rename` - rename fields https://github.com/ConduitIO/conduit/pull/1371
  - [x] `field.convert` - convert one type into another in a structured payload https://github.com/ConduitIO/conduit/pull/1371
  - [x] `filter` - ack record and remove it from the pipeline https://github.com/ConduitIO/conduit/pull/1371
  - [x] `avro.encode` - encode structured data into Avro data https://github.com/ConduitIO/conduit/pull/1401
  - [x] `avro.decode` - decode Avro data into structured data https://github.com/ConduitIO/conduit/pull/1410
  - [ ] `json.encode` - encode structured data into a JSON string
  - [x] `json.decode` - decode a JSON string into structured data https://github.com/ConduitIO/conduit/pull/1405
  - [x] `unwrap.kafkaconnect` - unwrap a Kafka Connect payload into the current record #1395 
  - [x] `unwrap.debezium` - unwrap a Debezium payload into the current record #1393 
  - [x] `unwrap.opencdc` - unwrap a OpenCDC payload into the current record #1387 
  - [x] `webhook.http` - send a HTTP request for each record #1382 
  - [x] `custom.javascript` - execute JavaScript code for each record https://github.com/ConduitIO/conduit/pull/1374
- Post-merge:
  - [ ] update docs, so that parameter docs don't start with field names: https://github.com/ConduitIO/conduit/pull/1382#pullrequestreview-1914283303
  - [ ] update built-in registry

**Comment by maha-hajja** [comment]
design doc https://github.com/ConduitIO/conduit/blob/main/docs/design-documents/20231117-better-processors.md
