### ISSUE TITLE
Feature: connector.yml

### ISSUE THREAD

**Issue by lovromazgon** [ConduitIO/conduit#1523]
We should extract the connector specifications into a YAML file instead of having it purely in Go code, to simplify use cases around extracting the data from specifications and using it in the connector readme or on conduit.io documentation pages.

Relevant discussion: https://github.com/ConduitIO/conduit/discussions/1522

#### Generate `connector.yaml` (the specification file)

This section covers all the work related to generating a `connector.yaml` for a connector. This is done by `specgen`, which lives in the Connector SDK.

- [x] https://github.com/ConduitIO/evolviconf/issues/1
- [x] https://github.com/ConduitIO/conduit-connector-sdk/pull/198 (specgen implementation, without tests)
- [x] https://github.com/ConduitIO/conduit-connector-sdk/pull/206
- [x] https://github.com/ConduitIO/conduit-connector-sdk/issues/210
- [x] https://github.com/ConduitIO/conduit-connector-sdk/issues/214
- [x] https://github.com/ConduitIO/conduit-connector-sdk/issues/209
- [x] https://github.com/ConduitIO/conduit-commons/pull/131

#### Documentation

This section covers documentation for the `specgen` tool itself.

- [x] https://github.com/ConduitIO/conduit-connector-sdk/issues/208
- [x] https://github.com/ConduitIO/conduit-site/issues/198
- [x] https://github.com/ConduitIO/conduit-connector-sdk/pull/115

#### Updates for new and existing connectors

This section covers work for updates related to new connectors (through our connector template) and existing connectors (by tracking upgrades to existing connectors using a tool that automates some of the work).

- [x] https://github.com/ConduitIO/conduit-connector-template/issues/57
- [x] https://github.com/ConduitIO/conduit-connector-template/issues/59
- [ ] (optional) https://github.com/ConduitIO/conduit-connector-template/issues/61
- [x] #2016
- [x] #2054

#### Generate connector documentation on conduit.io

This section covers work for generating connector documentation (using the `connector.yaml` file) and putting it on our website.

- [x] https://github.com/ConduitIO/conduit-site/issues/167
