### ISSUE TITLE
Transform: Javascript Transform

### ISSUE THREAD

**Issue by neovintage** [ConduitIO/conduit#19]
As the name implies :-)

- [ ] ~https://github.com/ConduitIO/conduit/issues/445~ 
We're punting on this, as the UI is not a priority at the moment. We'll focus on getting the JS transforms into Conduit through pipeline config files. See: https://github.com/ConduitIO/conduit/issues/32
- [x] https://github.com/ConduitIO/conduit/issues/446
- [x] https://github.com/ConduitIO/conduit/issues/447
- [x] https://github.com/ConduitIO/conduit/issues/448

**Comment by hariso** [comment]
@neovintage We are done with the planned tasks here (we're punting on the UI work for the time being). Are we good to close this issue?

**Comment by uchennakevinm1** [comment]
seems done to me. @neovintage this is all good!
