### ISSUE TITLE
Epic: +CLI -UI

### ISSUE THREAD

**Issue by raulb** [ConduitIO/conduit#1911]
As discussed in [this design document,](https://github.com/ConduitIO/conduit/discussions/1642) a Conduit CLI is what we believe should provide the developer experience our Conduit users need.

This issue will tackle all the necessary work to make a Conduit CLI a reality as part of [Conduit 0.13](https://github.com/ConduitIO/conduit/milestone/15).

> [!IMPORTANT]  
> While adding a new way to interact with Conduit, we'll **deprecate** the UI. There isn't feature parity at the moment and we strongly believe the CLI will be enough for now 

### -UI

- [x] https://github.com/ConduitIO/conduit/pull/1916
- [x] https://github.com/ConduitIO/conduit/pull/1917
- [x] Delete `UI` and `javascript` label [from conduit](https://github.com/ConduitIO/conduit/issues/labels)
- [x] conduit: remove UI code (https://github.com/ConduitIO/conduit/pull/2036)
- [x] conduit: remove [UI GitHub workflows](https://github.com/ConduitIO/conduit/tree/main/.github/workflows) (https://github.com/ConduitIO/conduit/pull/2036)
- [x] Archive, updating description of https://github.com/ConduitIO/mx-ui-components https://github.com/ConduitIO/mx-ui-components/pull/209

#### Does not require having Conduit running

- [x] https://github.com/ConduitIO/conduit/issues/1926
- [x] https://github.com/ConduitIO/ecdysis
- [x] https://github.com/ConduitIO/conduit/issues/1981
- [x] https://github.com/ConduitIO/conduit/issues/2017
- [x] https://github.com/ConduitIO/conduit/issues/2029
- [x] https://github.com/ConduitIO/conduit/issues/2018
- [x] https://github.com/ConduitIO/conduit/issues/2034
- [x] #2095

#### Requires having Conduit running

- [x] https://github.com/ConduitIO/conduit/issues/2019
- [x] https://github.com/ConduitIO/conduit/issues/2021
- [x] https://github.com/ConduitIO/conduit/issues/2025
- [x] https://github.com/ConduitIO/conduit/issues/2027
- [x] https://github.com/ConduitIO/conduit/issues/2023
- [x] https://github.com/ConduitIO/conduit/issues/2020
- [x] https://github.com/ConduitIO/conduit/issues/2022
- [x] https://github.com/ConduitIO/conduit/issues/2026
- [x] https://github.com/ConduitIO/conduit/issues/2024
- [x] https://github.com/ConduitIO/conduit/issues/2028
- [x] #2091
- [x] #2093
- [x] #2094

#### Bugs

- [x] https://github.com/ConduitIO/conduit/issues/2062
- [x] https://github.com/ConduitIO/conduit/issues/2067
- [x] https://github.com/ConduitIO/conduit/issues/2090
- [x] #2092
- [x] #2112

### Documentation changes

- [x] https://github.com/ConduitIO/conduit-site/issues/219
- [x] #2108
- [x] ConduitIO/conduit#2065
- [x] ConduitIO/conduit-site#212

### Nice to have

- [x] https://github.com/ConduitIO/conduit/issues/2037

### After the 0.13.0 release

- [x] Close https://github.com/ConduitIO/conduit/discussions/1642 posting an update.
- [x] Document [spf13/cobra's list of projects](https://github.com/spf13/cobra/blob/main/site/content/projects_using_cobra.md) if we use Cobra like we did with Meroxa's.
- [x] Close the loop on https://github.com/ConduitIO/conduit/discussions/247.

**Comment by raulb** [comment]
I just deleted both `UI` and `javascript` labels from [Conduit](https://github.com/ConduitIO/conduit/issues/labels). I ensured there were no open issues tagged with those.

**Comment by raulb** [comment]
I'll wait until we have the blog post published to communicate externally.

**Comment by raulb** [comment]
Posted here https://github.com/spf13/cobra/pull/2230.
