### ISSUE TITLE
Epic: Improving Conduit’s documentation

### ISSUE THREAD

**Issue by raulb** [ConduitIO/conduit#1919]
This is a placeholder created on Conduit's repository so we could tie it to the 0.13 release however, won't necessarily be _released_. Here some issues we've identified already:

- [x] https://github.com/ConduitIO/conduit-site/issues/156
- [x] https://github.com/ConduitIO/conduit-site/issues/151
- [x] https://github.com/ConduitIO/conduit-site/issues/150
- [x] https://github.com/ConduitIO/conduit-site/issues/146
- [x] https://github.com/ConduitIO/conduit-site/issues/171
- [x] https://github.com/ConduitIO/conduit-site/pull/191
- [x] https://github.com/ConduitIO/conduit-site/issues/167
- [x] https://github.com/ConduitIO/conduit-site/issues/177

### Not part of 0.13.0

> [!NOTE]  
> The items below were originally considered as part of this EPIC, but will be finished in a different iteration to make sure we finish the 0.13.0 in a timely fashion.

- [ ] https://github.com/ConduitIO/conduit-site/issues/149
- [ ] https://github.com/ConduitIO/conduit-site/issues/147
- [ ] https://github.com/ConduitIO/conduit-connector-sdk/pull/115
- [ ] https://github.com/ConduitIO/conduit-site/issues/176
- [ ] https://github.com/ConduitIO/conduit-site/issues/192
- [ ] https://github.com/ConduitIO/conduit-site/issues/193
- [ ] https://github.com/ConduitIO/conduit-site/issues/187

**Comment by simonl2002** [comment]
@raulb you still working on this?

**Comment by raulb** [comment]
Remaining required item we identified as necessary for the 0.13 release has been already done. We'll work on the remaining items (still linked to this EPIC, though they could be removed) independently. They're still open so we won't lose track of them.
