### ISSUE TITLE
Performance Benchmarks

### ISSUE THREAD

**Issue by neovintage** [ConduitIO/conduit#22]
While everyone should do their own benchmarking, we need to give developers some where to start. This will anchor expectations and then we can help folks tune their installations as they progress.

**Comment by hariso** [comment]
Checklist:

- [ ] Ability to run the benchmark manually
- [ ] Print msg/s, bytes/s
- [ ] Verify that pipeline time is correct (i.e. that we have correctly calculated the amount of time records are in the pipeline itself)
- [ ] Add more options for the generator (big payloads)

**Comment by hariso** [comment]
Code moved to https://github.com/ConduitIO/streaming-benchmarks.

**Comment by neovintage** [comment]
Complete!
