### ISSUE TITLE
Feature: Schema Registry support

### ISSUE THREAD

**Issue by ahmeroxa** [ConduitIO/conduit#984]
### Subtasks

- [x] https://github.com/ConduitIO/conduit/issues/1048
- [x] https://github.com/ConduitIO/conduit/issues/1041
- [x] https://github.com/ConduitIO/conduit/issues/1042
- [x] https://github.com/ConduitIO/conduit/issues/1043
- [x] https://github.com/ConduitIO/conduit/issues/1044
- [x] https://github.com/ConduitIO/conduit/issues/1045

### Feature description

Native support for the [Confluent Schema Registry](https://docs.confluent.io/platform/current/schema-registry/index.html) API should be added.

This will allow the Kafka connector to translate incoming encoded messages (e.g. Avro) to structured data so that they may be processed by _processors_ as well as be emitted downstream in other formats (e.g. OpenCDC/JSON).

Similarly, the connector will be able to produce data to destination Kafka clusters in encoded formats and register the schema automatically with a provided Schema Registry so that it may be used by downstream consumers.

My request would be to initially ship support for at least Avro but I suspect that supporting the full suite will not be much more effort (Avro, protobuf and JSON Schema).

This would additionally add support for the [Apicurio Registry](https://github.com/Apicurio/apicurio-registry) as it exposes a Confluent Schema Registry compatible API.

**Comment by lovromazgon** [comment]
Here are some takeaways from our discussion:
- Conduit should provide a processor that can take a schema from a schema registry and parse the raw payload into a structured payload.
- Schemas should be cached in Conduit (we should fetch a schema from the registry only the first time we encounter it).
- The user should be able to configure the schema subject based on record metadata (maybe using a Go template? e.g. `my-static-prefix-{{record.Metadata["topic"]}}`).
- By default, the processor should use a predefined metadata field as the schema subject (e.g. `schema-subject`), unless configured otherwise by the user (as mentioned in the previous point). Connectors can populate this metadata field if the resource that they connect provides the info or if there's a convention (e.g. the Kafka connector can follow the same convention as Kafka Connect).
- If a schema is not found the processor should fail.

**Comment by lovromazgon** [comment]
It's actively being worked on and should be included in the next release.

**Comment by lovromazgon** [comment]
Done, documentation is prepared here https://github.com/ConduitIO/conduit-site/pull/37.

**Comment by gedw99** [comment]
hey,

@lovromazgon  @ahmeroxa 

Not sure if your interested, but NATS JetStream also has translate support too.
So for example it can translate incoming encoded messages (e.g. Avro), etc.

Also is a nats translate package: https://github.com/metatexx/msgcvt that i use.
