### ISSUE TITLE
"Better Processors"

### ISSUE THREAD

**Issue by neovintage** [ConduitIO/conduit#997]
### Feature description

Our plan is for the better processor work for 0.8.0 to include.

- [x] #1284
- [x] #1285
- [x] #1286
- [x] #1158
- [x] #1162
- [x] #1156
- [x] #1287
- [x] #1288
- [x] #1289
- [x] #1290
~- [ ] #1291~
- [x] #1292
~- [ ] Update documentation~

What we currently aren't planning on including in this first pass:
- discovery of processor types (stretch goal)
- open cdc unwrap
- permanent storage
- Splitting and combining records
- Embedded processors

**Comment by simonl2002** [comment]
This likely won't be in 0.7.0 but the goal is to start the work on this.

**Comment by nassor** [comment]
Extra features descriptions:
* [ ] Load Processor as plugins as we do with connectors. With that, we could create custom processors for deployments.
* [ ] Have the Processor interface method `Close` called when Conduit is turning off, so we can release external resources allocated by the Processor
* [ ] Open Telemetry Support: send & return [`SpanContext`](https://opentelemetry.io/docs/specs/otel/trace/api/#spancontext) to the processor (and connectors as well).
* [ ] Simple Key/Value storage for processors.

**Comment by lovromazgon** [comment]
Relevant discussion: https://github.com/ConduitIO/conduit/discussions/1141

**Comment by raulb** [comment]
Documentation will be tackled in this other issue https://github.com/ConduitIO/conduit/issues/1422.

Closing this issue since yesterday "better processors" was shipped as part of [0.9.0](https://github.com/ConduitIO/conduit/releases/tag/v0.9.0).
